export enum DriverStatus {
  active = 'active',
  inactive = 'inactive'
}

export enum WindowType {
  soft = 'soft',
  hard = 'hard',
  none = 'none'
}

export enum RouteItemActionType {
  CUSTOMERS_NOT_ANSWERING = 'CUSTOMERS_NOT_ANSWERING',
  CUSTOMERS_REQUESTING_DELIVERY_CANCELLATIONS = 'CUSTOMERS_REQUESTING_DELIVERY_CANCELLATIONS',
  CUSTOMERS_REQUESTING_LOGISTICS_CHANGES = 'CUSTOMERS_REQUESTING_LOGISTICS_CHANGES',
  CUSTOMERS_REQUESTING_A_CALL_FROM_CX = 'CUSTOMERS_REQUESTING_A_CALL_FROM_CX',
  DRIVERS_REQUESTING_DELIVERY_LOCATION_UPDATES = 'DRIVERS_REQUESTING_DELIVERY_LOCATION_UPDATES',
  CUSTOMERS_NOT_RETURNING_COOLER_BAGS = 'CUSTOMERS_NOT_RETURNING_COOLER_BAGS'
}
