export enum ShiftActionType {
    STARTED_SHIFT = 'STARTED_SHIFT',
    STARTED_DELIVERING = 'STARTED_DELIVERING',
    FINISHED_SHIFT = 'FINISHED_SHIFT'
  }
  
  export enum Kitchen {
    // XX000 -> for pre-launch
    BH0 = 'BH000',
    BH1 = 'BH001',
    SA0 = 'SA000',
    SA1 = 'SA001',
    SA2 = 'SA002',
    KW0 = 'KW000',
    KW1 = 'KW001',
    QA0 = 'QA000',
    QA1 = 'QA001',
    AE0 = 'AE000',
    AE1 = 'AE001',
    OM0 = 'OM000',
    OM1 = 'OM001',
    GB0 = 'GB000',
    GB1 = 'GB001',
    // Any other country
    NA0 = 'NA000'
  }

  export enum Country {
    AE = 'AE',
    BH = 'BH',
    KW = 'KW',
    OM = 'OM',
    QA = 'QA',
    SA = 'SA',
    US = 'US',
    GB = 'GB'
  }
  
  export enum DeliveryTime {
    evening = 'evening',
    morning = 'morning',
    earlyMorning = 'earlyMorning'
  }

  export enum WindowType {
    soft = 'soft',
    hard = 'hard',
    none = 'none'
  }
  
  export enum DataType {
    onboarding = 'onboarding',
    foodPackageElement = 'foodPackageElement',
    foodPackage = 'foodPackage',
    ticket = 'ticket',
    employeePerks = 'employeePerks',
    addonsMenu = 'addonsMenu',
    addonsSubscriptionMenu = 'addonsSubscriptionMenu',
    healthyHabit = 'healthyHabit',
    challengeList = 'challengeList',
    biometric = 'biometric',
    connection = 'connection',
    coupon = 'coupon',
    caloCoupon = 'coupon#calo',
    mealoCoupon = 'coupon#mealo',
    delivery = 'delivery',
    driverMetrics = 'driverMetrics',
    dayProgress = 'dayProgress',
    email = 'email',
    estimatedDeliveries = 'estimatedDeliveries',
    food = 'food',
    foodComponent = 'foodComponent',
    foodComponentFoodMap = 'foodComponentFoodMap',
    foodPreference = 'foodPreference',
    customMacrosFoodPreference = 'customMacrosFoodPreference',
    invitationCode = 'invitationCode',
    ingredient = 'ingredient',
    invoice = 'invoice',
    kitchen = 'kitchen',
    log = 'log',
    menu = 'menu',
    map = 'map',
    subscription = 'subscription',
    subscriptionGift = 'subscriptionGift',
    newSubscription = 'newSubscription',
    paymentLock = 'paymentLock',
    rating = 'rating',
    routePlan = 'routePlan',
    routePlanNew = 'routePlanNew',
    supplyCapacityCount = 'supplyCapacityCount',
    userGroup = 'userGroup',
    wallet = 'wallet',
    waitingList = 'waitingList',
    ramadanList = 'ramadanList2026',
    kitchenLog = 'kitchenLog',
    settings = 'settings',
    menuGeneration = 'menuGeneration',
    subscriptionEndedEvent = 'subscriptionEndedEvent',
    groupGift = 'groupGift',
    groupGiftItem = 'groupGiftItem',
    deliveryEta = 'deliveryEta',
    inventoryItemMapping = 'inventoryItemMapping',
    nonConfirmedSubscription = 'nonConfirmedSubscription',
    waitingListPositionAttempt = 'waitingListPositionAttempt',
    failedAutoRenewAttempt = 'failedAutoRenewAttempt',
    modifiedDelivery = 'modifiedDelivery',
    dayProgressUserFood = 'dayProgressUserFood',
    user = 'user',
    donation = 'donation',
    consultationConfig = 'consultationConfig',
    habit = 'habit',
    habitChallenge = 'habitChallenge',
    habitChallengeProgress = 'habitChallengeProgress',
    notification = 'notification',
    notificationPreference = 'notificationPreference',
    scheduledNotification = 'scheduledNotification',
    nutritionTrackerFood = 'nutritionTrackerFood',
    weightTrackerProgress = 'weightTrackerProgress',
    waterTracker = 'waterTracker',
    waterTrackerIntake = 'waterTrackerIntake',
    stepsTracker = 'stepsTracker',
    dailySteps = 'dailySteps',
    complaint = 'complaint',
    challengePrize = 'challengePrize',
    challenge = 'challenge',
    challengeDay = 'challengeDay',
    gift = 'gift',
    kdsUserGroup = 'kdsUserGroup',
    cleverTapSegment = 'cleverTapSegment',
    gymMembership = 'gymMembership',
    precoroCache = 'precoroCache',
    mealDailyStatsSnapshot = 'mealDailyStatsSnapshot',
    ingredientDailyStatsSnapshot = 'ingredientDailyStatsSnapshot',
    componentDailyStatsSnapshot = 'componentDailyStatsSnapshot',
    kitchenFoodSizesPercentages = 'kitchenFoodSizesPercentages',
    precoroSKUCosts = 'precoroSKUCosts',
    routingConfig = 'routingConfig',
    consultationLog = 'consultationLog',
    affiliate = 'affiliate',
    affiliatePayout = 'affiliatePayout',
    driver = 'driver',
    deliveryTicket = 'deliveryTicket',
    complaintType = 'complaintType',
    deliveryComplaint = 'deliveryComplaint',
    cacheSettings = 'cacheSettings',
    loyaltyRewards = 'loyaltyRewards',
    supplyChainReport = 'supplyChainReport',
    invitationCodeStats = 'invitationCodeStats',
    invoiceCodes = 'invoiceCodes',
    menuStats = 'menuStats',
    routeAnalysis = 'routeAnalysis',
    coolerBag = 'coolerBag',
    coolerBagDocument = 'coolerBagDocument',
    scrapedSupplierProduct = 'scrapedSupplierProduct'
  }
  